import { sql } from "drizzle-orm";
import {
  index,
  jsonb,
  pgTable,
  text,
  timestamp,
  varchar,
  integer,
  boolean,
  date,
} from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

// Session storage table - Required for Replit Auth
export const sessions = pgTable(
  "sessions",
  {
    sid: varchar("sid").primaryKey(),
    sess: jsonb("sess").notNull(),
    expire: timestamp("expire").notNull(),
  },
  (table) => [index("IDX_session_expire").on(table.expire)]
);

// User storage table - Required for Replit Auth
export const users = pgTable("users", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  email: varchar("email").unique(),
  firstName: varchar("first_name"),
  lastName: varchar("last_name"),
  profileImageUrl: varchar("profile_image_url"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export type UpsertUser = typeof users.$inferInsert;
export type User = typeof users.$inferSelect;

// Customers table - Insurance customers
export const customers = pgTable("customers", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  surecDurumu: varchar("surec_durumu"),
  islemListesi: varchar("islem_listesi"),
  sonucIslemTipi: varchar("sonuc_islem_tipi"),
  bitTarih: date("bit_tarih"),
  anaBrans: varchar("ana_brans"),
  araBrans: varchar("ara_brans"),
  unvan: varchar("unvan").notNull(),
  musteriTemsilcisi: varchar("musteri_temsilcisi"),
  sube: varchar("sube"),
  listeGrupAdi: varchar("liste_grup_adi"),
  meslekGrubu: varchar("meslek_grubu"),
  plaka: varchar("plaka"),
  ruhsatNo: varchar("ruhsat_no"),
  policeTipi: varchar("police_tipi"),
  policeNo: varchar("police_no"),
  gorevliTemsilci: varchar("gorevli_temsilci"),
  produktorAdi: varchar("produktor_adi"),
  policeAciklamasi: text("police_aciklamasi"),
  grupKodu: varchar("grup_kodu"),
  kvkk: varchar("kvkk"),
  sonIslemTarihi: date("son_islem_tarihi"),
  kayitTarihi: date("kayit_tarihi"),
  veriKaynagi: varchar("veri_kaynagi"),
  portfoyKaynagi: varchar("portfoy_kaynagi"),
  tcKimlikNo: varchar("tc_kimlik_no"),
  vergiNo: varchar("vergi_no"),
  gsmNo: varchar("gsm_no"),
  ePosta: varchar("e_posta"),
  sehir: varchar("sehir"),
  ilce: varchar("ilce"),
  dogumTarihi: date("dogum_tarihi"),
  cinsiyet: varchar("cinsiyet"),
  aracMarka: varchar("arac_marka"),
  aracModel: varchar("arac_model"),
  aracModelYili: integer("arac_model_yili"),
  policeBitisTarihi: date("police_bitis_tarihi"),
  policeBaslangicTarihi: date("police_baslangic_tarihi"),
  tanzimTarihi: date("tanzim_tarihi"),
  iptalNedeni: varchar("iptal_nedeni"),
  iptalTarihi: date("iptal_tarihi"),
  primTutari: integer("prim_tutari"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const insertCustomerSchema = createInsertSchema(customers).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});
export type InsertCustomer = z.infer<typeof insertCustomerSchema>;
export type Customer = typeof customers.$inferSelect;

// Insurance Products table
export const products = pgTable("products", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  name: varchar("name").notNull(),
  category: varchar("category").notNull(),
  description: text("description"),
  targetAudience: varchar("target_audience"),
  isActive: boolean("is_active").default(true),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const insertProductSchema = createInsertSchema(products).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});
export type InsertProduct = z.infer<typeof insertProductSchema>;
export type Product = typeof products.$inferSelect;

// Segments table
export const segments = pgTable("segments", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  name: varchar("name").notNull(),
  description: text("description"),
  filterCriteria: jsonb("filter_criteria"),
  customerCount: integer("customer_count").default(0),
  aiInsight: text("ai_insight"),
  behaviors: jsonb("behaviors"),
  isAutoGenerated: boolean("is_auto_generated").default(false),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const insertSegmentSchema = createInsertSchema(segments).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});
export type InsertSegment = z.infer<typeof insertSegmentSchema>;
export type Segment = typeof segments.$inferSelect;

// Campaigns table
export const campaigns = pgTable("campaigns", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  name: varchar("name").notNull(),
  description: text("description"),
  segmentId: varchar("segment_id"),
  status: varchar("status").default("draft"),
  targetCustomerCount: integer("target_customer_count").default(0),
  contactedCount: integer("contacted_count").default(0),
  convertedCount: integer("converted_count").default(0),
  startDate: date("start_date"),
  endDate: date("end_date"),
  campaignType: varchar("campaign_type"),
  notes: text("notes"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const insertCampaignSchema = createInsertSchema(campaigns).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});
export type InsertCampaign = z.infer<typeof insertCampaignSchema>;
export type Campaign = typeof campaigns.$inferSelect;

// AI Analysis Results table
export const aiAnalyses = pgTable("ai_analyses", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  analysisType: varchar("analysis_type").notNull(),
  title: varchar("title").notNull(),
  insight: text("insight"),
  confidence: integer("confidence"),
  category: varchar("category"),
  customerIds: jsonb("customer_ids"),
  segmentId: varchar("segment_id"),
  metadata: jsonb("metadata"),
  isActive: boolean("is_active").default(true),
  createdAt: timestamp("created_at").defaultNow(),
});

export const insertAiAnalysisSchema = createInsertSchema(aiAnalyses).omit({
  id: true,
  createdAt: true,
});
export type InsertAiAnalysis = z.infer<typeof insertAiAnalysisSchema>;
export type AiAnalysis = typeof aiAnalyses.$inferSelect;
